Database

----------------------
- what is databse?
  - database server - RDBMS / DBMS / Nosql (mongodb)
    - Database
      - Table
        - Rows and columns 
      
- Install Postgresql
https://www.tecmint.com/install-postgresql-and-pgadmin-in-ubuntu/
- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
- sudo apt update
- wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
- sudo apt-get update
- sudo apt-get -y install postgresql
- sudo apt install postgresql-contrib
- To Install pgAdmin4
- curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
- sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
- sudo apt update
- sudo apt install pgadmin4
- sudo /usr/pgadmin4/bin/setup-web.sh
- http://SERVER_IP/pgadmin4 

- After installation
- sudo su - postgres
- psql
- Run following queries
CREATE USER tecmint WITH PASSWORD 'securep@wd';
CREATE DATABASE tecmintdb;
GRANT ALL PRIVILEGES ON DATABASE tecmintdb to tecmint;
\q 
ALTER USER user_name CREATEDB CREATEROLE LOGIN; 
-------------------------------------------
